snulion8th/accounts/urls.py
from django.conf.urls import include
from django.urls import path
from accounts import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

snulion8th/feedpage/urls.py
from django.urls import path
from feedpage import views

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'), # 추가
    path('<int:id>/edit', views.edit, name='edit'), 
    path('<int:id>/', views.show, name='show'), # 추가
    path('<int:id>/delete', views.delete, name='delete'), # 추가
    path('<int:id>/comments/', views.create_comment, name='create_comment'),
    path('<int:id>/comments/<int:cid>/', views.delete_comment, name='delete_comment'),
    path('<int:pk>/like/', views.feed_like, name='like'),
    path('<int:pk>/follow/', views.follow_manager, name='follow'), #추가
]

snulion8th/snulion8th/urls.py
from django.contrib import admin
from django.urls import path
import feedpage.views
from django.conf.urls import include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', feedpage.views.index, name='index'),
    path('feeds/', include('feedpage.urls')), 
    path('accounts/', include('accounts.urls')), #추가
]

snulion8th/accounts/models.py
from django.db import models

# Create your models here.

snulion8th/feedpage/models.py
# ./feedpage/models.py
from django.db import models
from django.utils import timezone # 장고는 created_at과 updated_at을 알아서 만들어 주지 않음. id는 만들어 줌
from django.contrib.auth.models import User   # 추가
from django.db.models.signals import post_save  # 추가
from django.dispatch import receiver   # 추가
# Create your models here.
class Feed(models.Model): # 모델 클래스명은 단수형을 사용 (Feeds(x) Feed(O))
    # id는 자동 추가
    title = models.CharField(max_length=256)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(blank=True, null=True)
    author = models.ForeignKey(User, null=True, on_delete= models.CASCADE)    
    liked_users = models.ManyToManyField(User, blank=True, related_name='feeds_liked', through='Like')

    def update_date(self): # 나중에 수정할 때 사용
        self.updated_at = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Profile(models.Model):   # 추가
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    college = models.CharField(max_length=20, blank=True)
    major = models.CharField(max_length=20, blank=True)
    follows = models.ManyToManyField('self', through = 'Follow', blank=True, related_name = 'followed', symmetrical=False)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):  
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):  
    instance.profile.save()


class FeedComment(models.Model):
    content = models.TextField()
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class Follow(models.Model): 
    follow_to = models.ForeignKey(Profile, related_name = 'follow_to', on_delete=models.CASCADE)
    follow_from = models.ForeignKey(Profile, related_name = 'follow_from', on_delete=models.CASCADE)

    def __str__(self):
        return '{} follows {}'.format(self.follow_from, self.follow_to)

snulion8th/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib import auth
from django.shortcuts import redirect
def signup(request):
    if request.method  == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
            auth.login(request, user)
            return redirect('/feeds')
    return render(request, 'accounts/signup.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username = username, password = password)
        if user is not None:
            auth.login(request, user)
            return redirect('/feeds')
        else:
            return render(request, 'accounts/login.html', {'error' : 'username or password is incorrect'})
    else:
        return render(request, 'registration/login.html')

def logout(request):
    return render(request, 'registration/logout.html')

snulion8th/feedpage/views.py
# ./feedpage/views.py
from django.shortcuts import render
from .models import Feed, FeedComment, Like, Follow, Profile  
from django.shortcuts import redirect # 추가
from django.contrib.auth.models import User

def index(request): # 원래 있던 index 함수 수정.
    if request.method == 'GET': # index
        feeds = Feed.objects.all()
        return render(request, 'feedpage/index.html', {'feeds': feeds})
        
    elif request.method == 'POST': # create(form을 이용하여 submit한 형태) 
        title = request.POST['title']
        content = request.POST['content']
        Feed.objects.create(title = title, content = content, author = request.user)
        return redirect('/feeds') 

def new(request):
    return render(request, 'feedpage/new.html')

def show(request,id): 

    feed=Feed.objects.get(id=id)
    return render(request,'feedpage/show.html',{'feed':feed})
        

def edit(request, id):

    if request.method == 'GET':
        feed = Feed.objects.get(id=id)
        return render(request, 'feedpage/edit.html', {'feed': feed})

    elif request.method == 'POST': 

        feed=Feed.objects.get(id=id)
        feed.title=request.POST['title']
        feed.content=request.POST['content']
        feed.save()
        return redirect('/feeds/'+str(id)) 

def delete(request, id):
    feed = Feed.objects.get(id=id)
    feed.delete()
    return redirect('/feeds')

def create_comment(request, id):
    content = request.POST['content']
    FeedComment.objects.create(feed_id=id, content=content, author = request.user)
    return redirect('/feeds')

def delete_comment(request, id, cid):
    c = FeedComment.objects.get(id=cid)
    c.delete()
    return redirect('/feeds')

def feed_like(request, pk):
    feed = Feed.objects.get(id = pk)
    like_list = feed.like_set.filter(user_id = request.user.id)
    if like_list.count() > 0:
        feed.like_set.get(user_id = request.user.id).delete()
    else:
        Like.objects.create(user_id = request.user.id, feed_id = feed.id)
    return redirect ('/feeds')


def follow_manager(request, pk):
    follow_from = Profile.objects.get(user_id = request.user.id)
    follow_to = Profile.objects.get(user_id = pk)

    try:
        following_already = Follow.objects.get(follow_from=follow_from, follow_to=follow_to)
    except Follow.DoesNotExist:
        following_already = None

    if following_already:
        following_already.delete()
    else:
        # Follow.objects.create(follow_from=follow_from, follow_to=follow_to)
        f = Follow()
        f.follow_from, f.follow_to = follow_from, follow_to
        f.save()

    return redirect('/feeds')

snulion8th/accounts/templates/accounts/signup.html
<h1> Sign Up! </h1>

<form method="POST" action="{%url 'signup'%}">
    {% csrf_token %}
    사용자 이름:
    <br>
    <input name="username" type="text" value="">
    <br>
    <br>
    비밀번호:
    <br>
    <input name="password1" type="password" value="">
    <br>
    <br>
    비밀번호 확인:
    <br>
    <input name="password2" type="password" value="">
    <br>
    <br>
    <input type="submit" value="Sign Up!">
</form>

snulion8th/feedpage/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Doobap</title>
  </head>
  <body>
        <header>
            <div style="text-align: right;">
                {% if user.is_authenticated %}
                    {{ user.get_username }}님, 안녕하세요
                    <a href="{% url 'logout'%}?next={{request.path}}">로그아웃</a>
                {% else %}
                    <a href="{% url 'signup' %}">회원가입</a>
                    <a href="{% url 'login'%}?next={{request.path}}">로그인</a>
                {% endif %}
            </div>
            <div style="text-align: right">                        
                내가 좋아한 글 : {{ user.feeds_liked.count }}개         
            </div>         
            Snulion Feeds
        </header>
        {% block content %}
        {% endblock %}
    </body>
</html>

snulion8th/feedpage/templates/feedpage/edit.html
{% extends 'base.html' %}

{% block content %}

<h1>edit feed</h1>
<form action="/feeds/{{ feed.id }}/edit" method="POST">
    {% csrf_token %}
    <p>title</p>
    <input name="title" value={{ feed.title }} /> <br />
    <p>content</p>
    <input name="content" value={{ feed.content }} /> <br />
    <input type="submit" value="수정하기" />
</form>


{% endblock content %}

snulion8th/feedpage/templates/feedpage/index.html
{% extends 'base.html' %}

{% block content %}

    <h1>feed page</h1>
    {% if user.is_authenticated %}      
        <a href = "/feeds/new"> new feed </a>
    {% endif %} 
    {% for feed in feeds %} 
        <div style="border: 1px solid grey;">
            <a href="/feeds/{{ feed.id }}/like">{{ feed.liked_users.count }} Likes</a>
            <a href="/feeds/{{ feed.id }}">더보기</a>
            {% if request.user == feed.author %} 
                <a href="/feeds/{{ feed.id }}/delete" onclick="return confirm('정말 삭제하시겠습니까?')" >삭제</a> 
            {% endif %}  
            <p>{{ feed.title }}</p>
            <p>{{ feed.content }}</p>
            <p>작성자:<strong>{{feed.author.username}}</strong>
                (following: {{ feed.author.profile.follow_to.all.count }} / follower: {{ feed.author.profile.follow_from.all.count }})
                {% if user.is_authenticated %}
                  {% if request.user != feed.author %}
                    <a href="/feeds/{{ feed.author.id }}/follow">
                      {% if request.user.profile not in feed.author.profile.follows.all %}
                          팔로우
                      {% else %}
                          팔로우 취소
                      {% endif %}
                    </a>
                  {% endif %}
                {% endif %}
            </p>
            {% for c in feed.feedcomment_set.all %}
                <p>{{ c.content }}</p>
                <form action="/feeds/{{ feed.id }}/comments/{{ c.id }}/" method="POST">
                    {% csrf_token %}
                    <button>댓글 삭제</button>
                </form>
            {% endfor %}
            <form action="/feeds/{{ feed.id }}/comments/" method="POST">
                {% csrf_token %}
                <input type="text" name="content" />
                <button type="submit">댓글 달기</button>
            </form>
        </div>
    {% endfor %} 

{% endblock content %}

snulion8th/feedpage/templates/feedpage/new.html
<h1>new feed</h1>
<form action="/feeds/" method="POST">
    {% csrf_token %}
    <p>title</p>
    <input name="title" /> <br />
    <p>content</p>
    <input name="content" /> <br />
    <input type="submit" value="submit" />
</form>

snulion8th/feedpage/templates/feedpage/show.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <a href="/feeds">home</a>
        <a href="/feeds/{{feed.id}}/edit">edit</a> 
        <p>{{ feed.title }}</p>
        <p>{{ feed.content }}</p>
    </div>
{% endblock content %}